version: '3.7'
services:
  postgres:
    image: postgres:15
    container_name: postgres_airflow
    restart: always
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=news_scraper
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  webserver:
    image: apache/airflow:2.5.0
    container_name: airflow_webserver
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/news_scraper
      - AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE=UTC
      - AIRFLOW__SMTP__SMTP_HOST=smtp.gmail.com
      - AIRFLOW__SMTP__SMTP_STARTTLS=True
      - AIRFLOW__SMTP__SMTP_SSL=False
      - AIRFLOW__SMTP__SMTP_USER=krishvamsi321@gmail.com
      - AIRFLOW__SMTP__SMTP_PASSWORD=remjawiwhycvtiwu
      - AIRFLOW__SMTP__SMTP_PORT=587
      - AIRFLOW__SMTP__SMTP_MAIL_FROM=krishvamsi321@gmail.com
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./logs:/usr/local/airflow/logs
      - ./config:/usr/local/airflow/config
    ports:
      - "8080:8080"
    command: webserver

  scheduler:
    image: apache/airflow:2.5.0
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/news_scraper
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./logs:/usr/local/airflow/logs
    command: scheduler

  smtp:
    image: namshi/smtp
    container_name: airflow_smtp
    restart: always
    ports:
      - "587:587"

volumes:
  postgres_data:
    driver: Local